language: julia
julia:
  - 1.1

branches:
 only: 
   - master
   - gh-pages

env: 
  global:
   - DOCUMENTER_DEBUG=true

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.build(); Pkg.test("SeisProcessing"; coverage=true)'

jobs:
  include:
   - stage: "Documentation"
     julia: 1.1
     os: linux
     script: 
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
